name: Release Workflow

on:
  workflow_call:
    inputs:
      specifier:
        description: 'The specifier for the workflow to call (e.g. major, minor, patch, etc.)'
        required: true
        default: 'patch'
        type: string
      use-python:
        description: 'Enable Python'
        required: false
        default: false
        type: boolean
      publish:
        description: 'Publish the release to NPM and PyPI'
        required: false
        default: true
        type: boolean
      pnpm-version:
        description: 'PNPM version'
        required: false
        default: '8'
        type: string
      node-version:
        description: 'Node version'
        required: false
        default: '20'
        type: string
      poetry-version:
        description: 'Poetry version'
        required: false
        default: '1.8.2'
        type: string
      python-version:
        description: 'Python version'
        required: false
        default: '3.9'
        type: string

permissions:
  actions: write
  id-token: write
  pull-requests: write
  issues: write
  statuses: write
  checks: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  release:
    name: Release ${{ inputs.specifier }}
    runs-on: ubuntu-latest
    steps:
      - uses: vm-x-ai/github-public-actions/.github/actions/setup-release@main
        id: setup_release
        with:
          use-python: ${{ inputs.use-python }}
          semantic-release-app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          semantic-release-private-key: ${{ secrets.SEMANTIC_RELEASE_PRIVATE_KEY }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          nx-cache-iam-role: ${{ vars.NXCACHE_IAM_ROLE }}
          nx-cache-aws-region: ${{ vars.NXCACHE_AWS_REGION }}
          pnpm-version: ${{ inputs.pnpm-version }}
          node-version: ${{ inputs.node-version }}
          poetry-version: ${{ inputs.poetry-version }}
          python-version: ${{ inputs.python-version }}

      - uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Release
        run: |
          if [ "${{ inputs.publish }}" = "true" ]; then
            pnpm nx release --yes ${{ inputs.specifier }}
          else
            pnpm nx release --skip-publish ${{ inputs.specifier }}
          fi
          git push --follow-tags
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          GITHUB_TOKEN: ${{ steps.setup_release.outputs.token }}
