name: Pull Request Checks

on:
  workflow_call:
    inputs:
      use-python:
        description: 'Enable Python'
        required: false
        default: false
        type: boolean

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: vm-x-ai/github-public-actions/.github/actions/setup-monorepo@main
        with:
          use-python: ${{ inputs.use-python }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.NXCACHE_IAM_ROLE }}
          aws-region: ${{ vars.NXCACHE_AWS_REGION }}
          role-session-name: NxCache

      - run: pnpm nx format:check
      - run: pnpm nx affected -t lint test build
