name: Pull Request Checks

on:
  workflow_call:
    inputs:
      use-python:
        description: 'Enable Python'
        required: false
        default: false
        type: boolean
      pnpm-version:
        description: 'PNPM version'
        required: false
        default: '8'
        type: string
      node-version:
        description: 'Node version'
        required: false
        default: '20'
        type: string
      poetry-version:
        description: 'Poetry version'
        required: false
        default: '1.8.2'
        type: string
      python-version:
        description: 'Python version'
        required: false
        default: '3.9'
        type: string

permissions:
  actions: write
  contents: read
  id-token: write

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: vm-x-ai/github-public-actions/.github/actions/setup-monorepo@main
        with:
          use-python: ${{ inputs.use-python }}
          pnpm-version: ${{ inputs.pnpm-version }}
          node-version: ${{ inputs.node-version }}
          poetry-version: ${{ inputs.poetry-version }}
          python-version: ${{ inputs.python-version }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.NXCACHE_IAM_ROLE }}
          aws-region: ${{ vars.NXCACHE_AWS_REGION }}
          role-session-name: NxCache

      - run: pnpm nx format:check
      - run: pnpm nx affected -t lint test build
