name: Set Up Monorepo
description: Set up nx monorepo for CI workflows

inputs:
  use-python:
    description: 'Enable Python'
    required: true
    default: false
    type: boolean
  pnpm-version:
    description: 'PNPM version'
    required: false
    default: '8'
    type: string
  node-version:
    description: 'Node version'
    required: false
    default: '20'
    type: string
  poetry-version:
    description: 'Poetry version'
    required: false
    default: '1.8.2'
    type: string
  python-version:
    description: 'Python version'
    required: false
    default: '3.9'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      if: ${{ inputs.use-python == 'true' }}
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2
      if: ${{ inputs.use-python == 'true' }}
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Use PNPM ${{ inputs.pnpm-version }}.x
      uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Use Node.js ${{ inputs.node-version }}.x
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install Node.js Dependencies
      shell: bash
      run: pnpm install

    - name: Install Python Dependencies
      if: ${{ inputs.use-python == 'true' }}
      shell: bash
      run: poetry install

    - uses: nrwl/nx-set-shas@v4
